### ISSUE TITLE
输入出发日期的时候报错

### ISSUE THREAD

**Issue by NBInfo** [jack030051/12306#2]
Traceback (most recent call last):
  File "test_12306_git.py", line 396, in <module>
    train_info = output_info()
  File "test_12306_git.py", line 48, in output_info
    results = getList()
  File "test_12306_git.py", line 42, in getList
    results = html.json()
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by NBInfo** [comment]
https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2018-12-26&leftTicketDTO.from_station=BJP&leftTicketDTO.to_station=HBB&purpose_codes=ADULT
200
Traceback (most recent call last):
  File "test_12306_git.py", line 396, in <module>
    train_info = output_info()
  File "test_12306_git.py", line 48, in output_info
    results = getList()
  File "test_12306_git.py", line 42, in getList
    results = html.json()
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\13716\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
